# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: S3Upload@1
  inputs:
    awsCredentials: 'AWS-S3-Connection'
    regionName: 'eu-west-2'
    bucketName: 'mytestazuredevopsbucket'
    globExpressions: '*yml'
    targetFolder: 'testfolder'
- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: 'AWS-S3-Connection'
    regionName: 'eu-west-2'
    stackName: 'vpc-stack'
    templateSource: 'file'
    templateFile: 'vpc_stack.yml'
